# Generated by Django 4.1.4 on 2023-01-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_studentdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentData',
        ),
    ]
