# Generated by Django 4.1.4 on 2023-01-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_delete_studentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parentname', models.CharField(max_length=200)),
                ('emailid', models.EmailField(max_length=200)),
                ('contact', models.CharField(max_length=10)),
                ('studentcg', models.CharField(max_length=2)),
            ],
        ),
    ]
