# Generated by Django 4.1.4 on 2023-01-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_studentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='regno',
            field=models.CharField(default='1RV20IS049', max_length=10),
            preserve_default=False,
        ),
    ]
