# Generated by Django 4.1.4 on 2023-01-29 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_studentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploaddata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
