# Generated by Django 4.1.4 on 2023-02-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_announcements'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploaddata1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('regno', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
