# Generated by Django 4.1.4 on 2023-02-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_uploaddata1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=10000)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Announcements',
        ),
        migrations.DeleteModel(
            name='uploaddata1',
        ),
    ]
