# Generated by Django 4.1.4 on 2023-02-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_announcements1_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendmailstudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yesno', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=200)),
            ],
        ),
    ]
