# Generated by Django 4.1.4 on 2023-02-24 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_sendmailstudents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sendmailstudents',
        ),
    ]
