# Generated by Django 4.1.4 on 2023-02-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_sendmailstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='sendmailstudents',
        ),
    ]
